version: "2"
linters:
  enable:
    - asciicheck
    - errorlint
    - gocritic
    - gosec
    - nilerr
  settings:
    errcheck:
      check-type-assertions: true
    gocritic:
      disabled-checks:
        - ifElseChain
        - assignOp
        - unlambda
        - exitAfterDefer
      disabled-tags:
        - experimental
        - opinionated
    gosec:
      excludes:
        - G404
    govet:
      disable:
        - shadow
        - fieldalignment
      enable-all: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - staticcheck
        path: _test\.go
    paths:
      - go-ethereum
      - fastcache
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/ethereum/go-ethereum)
        - prefix(github.com/offchainlabs)
  exclusions:
    generated: lax
    paths:
      - go-ethereum
      - fastcache
      - third_party$
      - builtin$
      - examples$
