name: Audit NPM packages

on:
  workflow_dispatch:
  pull_request:
  merge_group:
  push:
    branches:
      - main
      - develop

jobs:
  yarn-audit:
    name: Audit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install node_modules
        uses: OffchainLabs/actions/node-modules/install@main
        with:
          cache-key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}-${{ matrix.node-version }}

      - name: Run audit
        run: yarn audit:ci
